name: Rust CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Install cargo-audit
        working-directory: src-tauri
        run: cargo install cargo-audit
      - name: Build
        working-directory: src-tauri
        run: cargo build  --verbose
      - name: Test
        working-directory: src-tauri
        run: cargo test  --verbose 
      - name: Clippy
        working-directory: src-tauri
        run: cargo clippy  --verbose -- -D warnings 
      - name: Audit
        working-directory: src-tauri
        run: cargo audit 
