name: Rust CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Navigate to src-tauri
        run: cd src-tauri\
      - name: Build
        run: cargo build --verbose --manifest-path src-tauri\Cargo.toml
      - name: Test
        run: cargo test --verbose --manifest-path src-tauri\Cargo.toml
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings --manifest-path src-tauri\Cargo.toml
      - name: Audit
        run: cargo audit --manifest-path src-tauri\Cargo.toml
